version: '3.8'
services:
  nest-api:
    image:
      # remote
      438767311855.dkr.ecr.ap-northeast-1.amazonaws.com/stageee-dockerize/backend
      # local
      # stageee-dockerize_nest-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres
    env_file:
      - .env

#   postgres:
#     image: postgres:14
#     container_name: postgresprisma
#     restart: always
#     ports:
#       - 5432:5432
#     env_file:
#       - .env
#     volumes:
#       - postgres:/var/lib/postgresql/data

# volumes:
#   postgres:
#     name: nest-prisma-docker-db
